// app/layout.tsx

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// It's good practice to set up fonts here
const inter = Inter({ subsets: ['latin'] });

// The metadata object configures the <head> tag
export const metadata: Metadata = {
  title: 'My Awesome App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}